# -*- coding: utf-8 -*-
"""K means project review code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_lItRZMPPahWU19gCUJC4o89LN24gnk
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# %matplotlib inline
sns.set_context('notebook')
plt.style.use('fivethirtyeight')
from warnings import filterwarnings
filterwarnings('ignore')

df=pd.read_excel(r'cust_data.xlsx',index_col=0)
print(df)

df.columns

df.shape

df.info()

df.isnull().sum()

sns.countplot(data=df,x='Orders')

sns.countplot(data=df,x='Gender')

plt.text(x = -0.1, y = df.Gender.value_counts()[1] + 40, s = str(round((df.Gender.value_counts()[1])*100/len(df.Gender),2)) + '%')
plt.text(x = 0.9, y = df.Gender.value_counts()[0] + 40, s = str(round((df.Gender.value_counts()[0])*100/len(df.Gender),2)) + '%')
plt.show()







